# Use lightweight Node image
FROM node:20-alpine

# App directory inside container
WORKDIR /app

# Copy package.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# App port
EXPOSE 5000

# Start server
CMD ["node", "server.js"]