name: Deploy backend app

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2775
          script: |
            cd /root/test-app
            mv Dockerfile DockerFile
            git pull origin master
            mv DockerFile Dockerfile
            docker compose down
            docker compose up -d --build
